# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebView_Lime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebView_Lime
  pod 'SnapKit', '~> 5.0.0'
  pod 'SVProgressHUD'

end
