# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example-RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-RxSwift
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

end
