# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Authentication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Authentication
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'KakaoSDKCommon', '~> 2.3.1'
  pod 'KakaoSDKAuth', '~> 2.3.1'
  pod 'KakaoSDKUser', '~> 2.3.1'

end
